### ISSUE TITLE
Vertical layout

### ISSUE THREAD

**Issue by entioentio** [vicompany/ezpz-flexbox-grid#20]
I've tried `.gid--vertical > .cell.cell--6 + .cell.cell--6` and, well, it's still setting width of the cells. I think it's worth to mention in the docs that you have to specify heights yourself :)

Cheers!

**Comment by svensigmond** [comment]
Hi @entioentio sorry for taking so much time to get back to you.

We recently discussed the documentation and name of the grid--vertical class and agree that neither of these make sufficiently clear that the EZPZ grid is a horizontal grid "only", but leverages the flex-direction property to be able to create a vertical layout. 

We are not planning to add further vertical options to the grid so the documentation will be updated shortly and the class name might be changed in the future.
