### ISSUE TITLE
When $ezpz-grid-default-content-stretch is left to default, grid breaks on IE10

### ISSUE THREAD

**Issue by sjorsjes** [vicompany/ezpz-flexbox-grid#32]
Hi guys,

When leaving the [$ezpz-grid-default-content-stretch](https://github.com/vicompany/ezpz-flexbox-grid/blob/master/docs/settings.md#ezpz-grid-default-content-stretch-string) to the default setting 'unstretch' the grid will break.

This is happening because IE can't handle '```.grid .cell { display: inline; }```. Changing this to inline-block seems to work?

**Comment by svensigmond** [comment]
The 3.0.1 release should fix this issue, thanks for reporting!

**Comment by sjorsjes** [comment]
Thanks!
