### ISSUE TITLE
Mixins

### ISSUE THREAD

**Issue by mmjaeger** [vicompany/ezpz-flexbox-grid#6]
Hello
Nice grid system - however, I was wondering whether you're planning to add some mixins so the grid systems could be used in a more unobtrusive way.

Thanks

**Comment by svensigmond** [comment]
Hello @mmjaeger , could you add a little more information about what you would like to see? I do not fully understand what kind of mixins you would like to see, but I definitely want to look into any requests we get.

Many thanks!

**Comment by mmjaeger** [comment]
Thanks for replying - here is a good article about what I mean by using
mixins to be able to have some more semantic classes:
https://zurb.com/expo/lessons/get-real-with-a-semantic-grid

On Wed, Apr 27, 2016 at 11:55 PM, svensigmond notifications@github.com
wrote:

> Hello @mmjaeger https://github.com/mmjaeger , could you add a little
> more information about what you would like to see? I do not fully
> understand what kind of mixins you would like to see, but I definitely want
> to look into any requests we get.
> 
> Many thanks!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/vicompany/ezpz-flexbox-grid/issues/6#issuecomment-215328242

## 

Marco M. Jaeger
http://net4visions.com

**Comment by svensigmond** [comment]
Thanks for clarifying, we will definitely look into it and see if we can implement this in the grid system.

**Comment by mmjaeger** [comment]
Sounds great - please keep me posted.

On Thu, Apr 28, 2016 at 7:22 AM, svensigmond notifications@github.com
wrote:

> Thanks for clarifying, we will definitely look into it and see if we can
> implement this in the grid system.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/vicompany/ezpz-flexbox-grid/issues/6#issuecomment-215441260

## 

Marco M. Jaeger
http://net4visions.com

**Comment by mmjaeger** [comment]
Any progress on the mixins

**Comment by ba55ie** [comment]
Not yet. It's also quite a big change, so it may take some time (if we implement it). You can always send us a pull request.

**Comment by ba55ie** [comment]
We are working on it. :)

**Comment by sjorsjes** [comment]
The mixins are now merged with the master
