### ISSUE TITLE
Grid wrapping

### ISSUE THREAD

**Issue by ba55ie** [vicompany/ezpz-flexbox-grid#7]
Make wrapping the default. My opinion is that grid cells should wrap to a new line when there isn't enough space. Just like all other grid systems.

Also the [demo](http://vicompany.github.io/ezpz-flexbox-grid/optional-features.html#wrapping-cells-default) does not seem to work on Firefox.

**Comment by sjorsjes** [comment]
If we make wrapping the default, it would be a breaking change. What we could do is add a property so you can make it the default by setting a bool.

**Comment by ba55ie** [comment]
Yep, @edw1n and I had the same idea about the boolean toggle.
