### ISSUE TITLE
Use Rawgit for demo

### ISSUE THREAD

**Issue by ba55ie** [vicompany/ezpz-flexbox-grid#8]
Generate a CSS file in the master branche and use this file, thru [RawGit](https://rawgit.com), for the demo (gh-pages branche). This way the demo will always be up to date and we don't need any build scripts in that branche.

**Comment by sjorsjes** [comment]
Since we are building custom css with _ezpz-flexbox-grid.scss partial we need to keep the source file in the github pages branch.
